-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 20:33:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sisben
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_sisben` ;

-- -----------------------------------------------------
-- Schema bd_sisben
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sisben` DEFAULT CHARACTER SET utf8 ;
USE `bd_sisben` ;

-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_user` (
  `id_user` INT(5) NOT NULL AUTO_INCREMENT,
  `nm_user` VARCHAR(45) NOT NULL,
  `pw_senha` VARCHAR(45) NOT NULL,
  `tp_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_prefeituras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_prefeituras` (
  `id_prefeitura` INT(5) NOT NULL AUTO_INCREMENT,
  `nm_prefeitura` VARCHAR(100) NOT NULL,
  `nu_cnpj` VARCHAR(20) NOT NULL,
  `fn_prefeitura` VARCHAR(15) NULL,
  `nu_cep` VARCHAR(10) NOT NULL,
  `nm_logradouro` VARCHAR(50) NOT NULL,
  `nu_numero` VARCHAR(6) NOT NULL,
  `nm_bairro` VARCHAR(50) NOT NULL,
  `nm_cidade` VARCHAR(50) NOT NULL,
  `sl_estado` VARCHAR(2) NOT NULL,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `pw_senha` VARCHAR(50) NOT NULL,
  `tp_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prefeitura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_assistenteSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_assistenteSocial` (
  `id_assistenteSocial` INT(5) NOT NULL AUTO_INCREMENT,
  `nm_assistenteSocial` VARCHAR(100) NOT NULL,
  `nu_cpf` VARCHAR(20) NOT NULL,
  `fn_assistenteSocial` VARCHAR(15) NULL,
  `nu_cep` VARCHAR(10) NOT NULL,
  `nm_logradouro` VARCHAR(50) NOT NULL,
  `nu_numero` VARCHAR(6) NOT NULL,
  `nm_bairro` VARCHAR(50) NOT NULL,
  `nm_cidade` VARCHAR(45) NOT NULL,
  `sl_estado` VARCHAR(2) NOT NULL,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `pw_senha` VARCHAR(50) NOT NULL,
  `tp_user` VARCHAR(45) NOT NULL,
  `id_prefeitura` INT(5) NOT NULL,
  PRIMARY KEY (`id_assistenteSocial`),
  INDEX `fk_tb_assistenteSocial_tb_prefeituras_idx` (`id_prefeitura` ASC),
  CONSTRAINT `fk_tb_assistenteSocial_tb_prefeituras`
    FOREIGN KEY (`id_prefeitura`)
    REFERENCES `bd_sisben`.`tb_prefeituras` (`id_prefeitura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_doador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_doador` (
  `id_doador` INT(5) NOT NULL AUTO_INCREMENT,
  `nm_doador` VARCHAR(100) NOT NULL,
  `tp_tipo` VARCHAR(45) NOT NULL,
  `nu_cpf_cnpj` VARCHAR(20) NOT NULL,
  `fn_doador` VARCHAR(15) NULL,
  `nu_cep` VARCHAR(10) NOT NULL,
  `nm_logradouro` VARCHAR(50) NOT NULL,
  `nu_numero` VARCHAR(6) NOT NULL,
  `nm_bairro` VARCHAR(50) NOT NULL,
  `nm_cidade` VARCHAR(50) NOT NULL,
  `sl_estado` VARCHAR(2) NOT NULL,
  `id_prefeitura` INT(5) NOT NULL,
  PRIMARY KEY (`id_doador`),
  INDEX `fk_tb_doador_tb_prefeituras1_idx` (`id_prefeitura` ASC),
  CONSTRAINT `fk_tb_doador_tb_prefeituras1`
    FOREIGN KEY (`id_prefeitura`)
    REFERENCES `bd_sisben`.`tb_prefeituras` (`id_prefeitura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_usuario` (
  `id_usuario` INT(5) NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(100) NOT NULL,
  `nu_cpf` VARCHAR(20) NOT NULL,
  `fn_usuario` VARCHAR(15) NULL,
  `nu_cep` VARCHAR(10) NOT NULL,
  `nm_logradouro` VARCHAR(50) NOT NULL,
  `nu_numero` VARCHAR(6) NOT NULL,
  `nm_bairro` VARCHAR(50) NOT NULL,
  `nm_cidade` VARCHAR(50) NOT NULL,
  `sl_estado` VARCHAR(2) NOT NULL,
  `nu_rg` VARCHAR(45) NULL,
  `dt_nascimento` VARCHAR(10) NOT NULL,
  `nu_renda` INT(10) NOT NULL,
  `nu_pis` VARCHAR(45) NULL,
  `nm_profissao` VARCHAR(45) NOT NULL,
  `tp_imovel` VARCHAR(45) NOT NULL,
  `tp_saneamento` VARCHAR(45) NOT NULL,
  `nu_deficiente` VARCHAR(10) NULL,
  `nu_dependentes` VARCHAR(10) NULL,
  `tp_status` VARCHAR(45) NOT NULL,
  `pw_senha` VARCHAR(50) NOT NULL,
  `tp_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_dependente` (
  `id_dependente` INT NOT NULL AUTO_INCREMENT,
  `nm_dependente` VARCHAR(45) NOT NULL,
  `tp_dependente` VARCHAR(45) NOT NULL,
  `nu_idade` VARCHAR(45) NOT NULL,
  `id_usuario` INT(5) NOT NULL,
  PRIMARY KEY (`id_dependente`),
  INDEX `fk_tb_dependente_tb_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tb_dependente_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_sisben`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sisben`.`tb_doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sisben`.`tb_doacao` (
  `id_doacao` INT(5) NOT NULL AUTO_INCREMENT,
  `te_descricao` VARCHAR(100) NOT NULL,
  `nm_doador` VARCHAR(45) NOT NULL,
  `dt_entrada` VARCHAR(45) NOT NULL,
  `dt_saida` VARCHAR(45) NULL,
  `tp_situacao` VARCHAR(45) NOT NULL,
  `id_usuario` INT(5) NOT NULL,
  PRIMARY KEY (`id_doacao`),
  INDEX `fk_tb_doacao_tb_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tb_doacao_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_sisben`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insere o usuário administrador do sistema
INSERT INTO `bd_sisben`.`tb_user` (`id_user`, `nm_user`, `pw_senha`, `tp_user`) VALUES (NULL, 'admin', 'admin', 'adm');